language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

python:
  - 2.7
  - 3.5
  - 3.6

env:
  global:
    - TEST_DIR=/tmp/tempfit
    - CONDA_DEPS="numpy scipy pytest pip"
    - PIP_DEPS="astroML gatspy coverage codecov pytest-cov"
    - CONDA_FORGE_DEPS="pynfft"

before_install:
    - export MINICONDA=$HOME/miniconda
    - export PATH="$MINICONDA/bin:$PATH"
    - hash -r
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -f -p $MINICONDA
    - conda config --set always_yes yes
    - conda update -q conda
    - conda info -a

install:
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION $CONDA_DEPS
  - source activate test-env
  - conda install -c conda-forge $CONDA_FORGE_DEPS
  - pip install $PIP_DEPS
  - python setup.py install

script:
  - mkdir -p $TEST_DIR
  - cd $TEST_DIR && py.test --pyargs tempfit --cov=tempfit

after_success:
  - codecov --token=a6cd5a9c-eec8-4785-807b-33fe46543957
